
platform:
  - x86
  - x64

install:
  - set FINAL_ARCH=64
  - if "%PLATFORM%" == "x86" set FINAL_ARCH=32
  - .\settings.bat %FINAL_ARCH% 12 Release
  - scripts\build.bat

build: off
test: off
deploy: off