
platform:
  - x86

install:
  - cinst wget
  - cinst msysgit
  - cinst curl
  - cinst 7zip
  - cinst cmake
  #- cinst python2
  - cinst GnuWin
  - settings.bat
  - scripts\02_download_packages.bat
  - scripts\03_build_icu.bat
  - scripts\04_build_boost.bat
  - scripts\04-1_extract_webp.bat

build: OFF

test: OFF

test_script: OFF

deploy: OFF
