
platform:
  - x86

install:
  # make sure nmake is on PATH
  - call "%VS120COMNTOOLS%\..\..\VC\vcvarsall.bat" x86
  - cinst wget
  - cinst msysgit
  #- cinst curl
  - cinst 7zip
  #- cinst cmake
  #- cinst python2
  #- cinst python2-x86_32
  #- cinst GnuWin
  - settings.bat
  #- scripts\build_icu.bat >%ROOTDIR%\icu.log 2>&1
  #- scripts\build_boost.bat
  - scripts\build_webp.bat
  - scripts\build_jpeg.bat
  - scripts\build_freetype.bat
  - scripts\build_zlib.bat
  - scripts\build_libpng.bat
  - scripts\build_libpq.bat
  - scripts\build_tiff.bat
  - scripts\build_libxml2.bat
  - scripts\build_protobuf.bat